import React from 'react'
import './Publications.css'

function Publications() {
    return (
        <div className="publication-section">
            <section className="publication-container">
                <div className="publication-title">Integrated log-aware CI/CD pipeline with custom bot for monitoring</div>
                <p className="publication-description">
                    {'“ Our aim is to come up with an improved CI/CD and monitoring process which is convenient for the developers to set up and leverage with the least amount of configuration and manual intervention. Additionally, it proposes a customizable python application to process and maintain the inherently complex logs generated by the pipeline, contributing to the ease of monitoring the pipeline. ”'}
                </p>
                <div className="publication-links">
                    {`Published in`}<br />{`2023 8th International Conference on Cloud Computing and Big Data Analytics (ICCCBDA)`}
                </div>
                <div className="publication-button-container">
                    <button className="publication-button">{'> '}Read Paper<span>_</span></button>
                </div>
            </section>
        </div>
    )
}

export default Publications